# .github/workflows/ci.yml
name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn clean test

      - name: Upload Cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber-html-reports/**

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p reports
          cp -r target/cucumber-reports/cucumber-html-reports/* reports/
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b gh-pages
          cp -r reports/* .
          git add .
          git commit -m "Deploy reports to GitHub Pages"
          git push origin gh-pages --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
