# .github/workflows/ci.yml
name: Github Actions Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn clean test

      - name: Upload Cucumber reports
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/cucumber-html-reports/**

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Prepare reports for GitHub Pages
        run: |
          mkdir -p reports
          cp -r target/cucumber-reports/cucumber-html-reports/* reports/
          cd reports
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          git add .
          git commit -m "Deploy reports to GitHub Pages"
          git push -u origin gh-pages --force

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./reports
          publish_branch: gh-pages
